kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      cloud-provider: "external"
      v: "5"
  controllerManager:
    extraArgs:
      cloud-provider: "external"
      v: "5"
  ---
  kind: InitConfiguration
  nodeRegistration:
    kubeletExtraArgs:
      cloud-provider: "external"
  ---
  kind: JoinConfiguration
  nodeRegistration:
    kubeletExtraArgs:
      cloud-provider: "external"
      v: "5"
nodes:
- role: control-plane
- role: worker
- role: worker